spring:
  data:
    redis:
      host: localhost
      port: 30100
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:aartifactiddb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---

spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: true

logging:
  level:
    com.ggroupid.aartifactid.core.usecase: DEBUG
    com.ggroupid.aartifactid.domain.model.TracingAspect: TRACE
