version: '3.8'

services:

  aartifactid:
    image: aartifactid
    build:
      context: .
      args:
        DOCKER_IMAGE_MAVEN: ${DOCKER_IMAGE_MAVEN}
        DOCKER_IMAGE_JAVA: ${DOCKER_IMAGE_JAVA}
        PROFILE: ${PROFILE}
    environment:
      PROFILE: ${PROFILE}
    network_mode: host
